language: python

python:
  - "3.8"

jobs:
  include:
    - stage: "Build Lab 2."
      name: "Run tests for Lab 2"
      python: 3.8
      install:
        - cd ./Lab2/
        - pipenv install
      script: pipenv run pytest tests/tests.py || true
    - stage: "Build Lab 3."
      name: "Run Djungo Server"
      python: 3.8
      install:
        - cd ./Lab3/
        - pipenv install
        - pipenv install requests
        - pipenv install django
      script: bash ./script/travis-build.sh
    - stage: "Build Lab 4."
      name: "Build Docker images & Home task"
      services:
        - docker
      install:
        - cd ./Lab4/
      script:
        - docker build -t vyacheslavbeltyukov/lab4:django-travis .
        - docker images
        - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo "$MY_PASSWORD" | docker login -u "$MY_USERNAME" --password-stdin; docker push vyacheslavbeltyukov/lab4:django-travis; else echo "PR skip deploy"; fi
    - stage: "Build Lab 5."
      name: "Build and run Docker images via make"
      services:
        - docker
      install:
        - cd ./Lab5/
        - make app
        - make tests
      script:
        - make run
        - make test-app
branches:
  only:
    - master
